version: "3.5"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-server
    hostname: mqtt-server
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "${MQTT_PORT}:1883"
      - "${MQTT_TLS_PORT}:8883"
    environment:
        TZ: ${TZ}
    networks:
      - default
    restart: unless-stopped

  influxdb:
    image: influxdb:latest
    container_name: influxdb-server
    hostname: influxdb-server
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
    networks:
      - default
 
  postgres:
    container_name: postgres-server
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - default
    restart: unless-stopped

volumes:
  influxdb-storage:
  postgres:
networks:
  default:
